<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>services score</name>
  <uuid>e3e5a06d-05a6-499a-a142-c2601615357e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
the number of elements in the Services requested
of
Services
is more than 3
then
add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
